name: Lighthouse check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lighthouse:
    name: Lighouse ${{ matrix.device}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        device: [mobile, desktop]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.15.x

      - name: Run Lighthouse CI
        run: lhci autorun --config=./config/lighthouse/lighthouserc.${{ matrix.device}}.cjs
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}

  # lhci:
  #   name: Lighthouse
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Use Node.js 24.x
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 24.x

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build app
  #       run: npm run build

  #     - name: Install Lighthouse CI
  #       run: npm install -g @lhci/cli@0.15.x

  #     - name: Run Lighthouse CI mobile
  #       run: lhci autorun --config=./config/lighthouse/lighthouserc.mobile.mjs
  #       env:
  #         LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}

  #     - name: Run Lighouse CI desktop
  #       run: lhci autorun --config=./config/lighthouse/lighthouserc.desktop.mjs
  #       env:
  #         LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
